version: '2'
services:
  db:
    image: mysql:5.7
    volumes:
      - "./.data/db:/var/lib/mysql"
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: raz0rpr00ty
      MYSQL_DATABASE: razorpay
      MYSQL_USER: razorpay
      MYSQL_PASSWORD: raz0rpaydev

  razorpay-binary:
    depends_on:
      - db
    image: razorpay/devops:latest
    links:
      - db
    ports:
      - "8080:8080"
    restart: always
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: razorpay
      MYSQL_PASS: raz0rpaydev
      GIN_MODE: release
      PORT: 8080
    command: ./rzp-interview
